spring.application.name=cuenta-service
server.port=8082

spring.datasource.url=jdbc:postgresql://banco-db:5432/banco
#spring.datasource.url=jdbc:postgresql://localhost:5432/banco
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.default_schema=servicio-cuentas
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#spring.rabbitmq.host=localhost
spring.rabbitmq.host=banco-rabbit
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest